# Generated by Django 5.0 on 2023-12-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iris',
            name='classifcation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
